### ISSUE TITLE
Demo GIF link is broken

### ISSUE THREAD

**Issue by JoaoGFarias** [arrow-kt/arrow-meta-examples#42]
The GIF link on the README file is broken.

https://github.com/arrow-kt/arrow-meta/raw/master/docs/img/demos/hello-world-compiler-plugin.gif
 
![image](https://user-images.githubusercontent.com/1585655/95458656-ba36b000-0972-11eb-9f4c-a66cdca63134.png)

**Comment by rachelcarmena** [comment]
Thank you so much @JoaoGFarias :raised_hands: Fixed!!
