### ISSUE TITLE
avoid code generation in source folder

### ISSUE THREAD

**Issue by henry1986** [arrow-kt/arrow-meta-examples#50]
I tried the hello world example of arrow meta and I am so far convinced of what I see.

With one exception - after doing a `./gradlew clean build`, I got a file "HelloWorld.kt.meta" in the src folder. That is nice for debug purpose, but bad in production.

Is there a way to avoid this file or at least to put it into the build folder? I didn't find a way to do that.

**Comment by henry1986** [comment]
Stupid me. Got the solution. In HelloWorld.kt

```
//metadebug

fun helloWorld(): Unit = TODO()



fun main() {
    helloWorld()
}
```

there is a `//metadebug` comment. Delete it, and no "HelloWorld.kt.meta" is generated.

**Comment by rachelcarmena** [comment]
Thanks @henry1986 ! Oh, no, please, don't feel bad about it. Maybe a warning message is missing. Please, all the contributions to improve the examples and to avoid misunderstandings are welcome!!

Thanks!! :raised_hands:
