### ISSUE TITLE
`syntheticScope`causes an error: `Unresolved reference: synthetic`

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [arrow-kt/arrow-meta-examples#56]
I have been playing with the generate source samples combined with the example in the docs to generate a local compiler plugin plus a consumer

When I run the project, I get this error:

```
Unresolved reference: synthetic
```

If I remove `syntethicScope`, it works:

```
val Meta.helloWorld: CliPlugin get() =
  "Hello World" {
    meta(
      namedFunction(this, { element.name == "helloWorld" }) { (c, _) ->  // <-- namedFunction(...) {...}
        Transform.replace(
          replacing = c,
          newDeclaration = """|fun helloWorld(): Unit =
                              |  println("Hello ΛRROW Meta!")
                              |""".function(descriptor)
								  .syntheticScope // delete this line
        )
      }
    )
  }
```

Is there any wrong with my setup?

I just copied the generate sources samples and I changed I bit the code to use `replace` instead of `newSources`.

**Comment by raulraja** [comment]
The synthetic scope is going away so feel free to ignore it for now. It will no longer be needed because the IDE part is gone and we are waiting for FIR and IDEA support in FIR compiler plugins in which case synthetic descriptors like this should not be needed.
